### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by NekoBelmont** [QwertyTheCoder/Minecraft-bedrock-cracked#127]
The log says:
Starting Operation:  Checking Version of System Dlls 
Detected 18362.1110
Ended Operation:  Checking Version of System Dlls

**Comment by randomidiot2887** [comment]
mee too. log says:

Starting Operation:  Checking Version of System Dlls 
Detected 19041.3636
Ended Operation:  Checking Version of System Dlls 

probabally becuse my windws version may be too new.

**Comment by randomidiot2887** [comment]
fixed mine. follow this for more.
download this
https://github.com/Max-RM/mcenterdlls/tree/main/18362.1110
and paste into the folders 
C:\ProgramData\MCenters\Methods\Dll\
paste the one in x64 into a folder you creat(if not there) named x64 and vice versa for the x86 version.
then it should work. i tried it and it fixed mine

**Comment by NekoBelmont** [comment]
> fixed mine. follow this for more. download this https://github.com/Max-RM/mcenterdlls/tree/main/18362.1110 and paste into the folders C:\ProgramData\MCenters\Methods\Dll paste the one in x64 into a folder you creat(if not there) named x64 and vice versa for the x86 version. then it should work. i tried it and it fixed mine
> 
> hope this helps

It did, thank you!

**Comment by AcAwesomeAndrew** [comment]
> fixed mine. follow this for more. download this https://github.com/Max-RM/mcenterdlls/tree/main/18362.1110 and paste into the folders C:\ProgramData\MCenters\Methods\Dll paste the one in x64 into a folder you creat(if not there) named x64 and vice versa for the x86 version. then it should work. i tried it and it fixed mine
> 
> hope this helps

this didnt work for me. I still have the same error. Not sure why.

**Comment by AcAwesomeAndrew** [comment]
I put the .dll in a folder labeled x64 inside the mcenters dll folder
